#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
sys.dont_write_bytecode = True
from pathlib import Path

from corelangdistribution2 import __version__
from corelangdistribution2.bench import run_bench, run_bench_matrix, run_real_bench, run_fastcdc_tuning_matrix, run_largefile_variant_matrix, run_adaptive_policy_bench, run_standalone_baselines_bench, run_heavy_change_matrix, run_hybrid_planner_bench, run_cost_aware_planner_bench, run_cost_aware_scenarios_bench, run_corpus_bench, render_static_report, run_network_pilot, run_mirror_pilot, run_object_store_pilot, run_signed_url_pilot, run_minio_pilot, run_minio_robustness_pilot, run_minio_full_baseline_pilot, run_minio_cost_matrix_pilot, run_anti_cherrypick_report_pilot, run_github_report_pilot, run_comparison_harness_pilot, run_rsync_baseline_pilot, run_zsync_baseline_pilot, make_light_zip, make_review_zip, cleanup_heavy_artifacts, BENCH_SCENARIOS, BENCH_PROFILES
from corelangdistribution2.repo import audit_install, cache_gc, rebuild_cache_index, repair_install, doctor_install, create_patch_plan, diff_repos, extract_file, fetch_install, inspect_repo, keygen, make_repo, root_init, sign_repo, verify_repo, release_check
from corelangdistribution2.server import serve
from corelangdistribution2.selftest import run_selftest
from corelangdistribution2.release import beta_report, dist_check, write_json_report


def emit(obj) -> None:
    print(json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False))


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="cld2", description="CoreLangDistribution 2.0 CLI")
    p.add_argument("--version", action="version", version=__version__)
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("pack", help="Pack a directory into a .cldrepo repository")
    s.add_argument("input_dir")
    s.add_argument("--out", required=True)
    s.add_argument("--release-id", default="dev")
    s.add_argument("--release-seq", type=int, default=0, help="Monotonic release sequence used by rollback guard")
    s.add_argument("--expires-at", help="Optional release expiry timestamp, e.g. 2035-01-01T00:00:00Z")
    s.add_argument("--not-before", help="Optional not-before timestamp, e.g. 2026-01-01T00:00:00Z")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="cdc")
    s.add_argument("--fixed-size", default="256KiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=16, help="Candidate scan stride for fastcdc; lower values improve reuse but cost more CPU")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="auto")
    s.add_argument("--force", action="store_true")

    s = sub.add_parser("inspect", help="Inspect a local or HTTP .cldrepo")
    s.add_argument("repo")

    s = sub.add_parser("verify", help="Verify metadata, pack hashes, chunks, and optionally Ed25519 trust signature / trusted-root policy")
    s.add_argument("repo")
    s.add_argument("--deep", action="store_true")
    s.add_argument("--trust-key", help="Verify signatures.json with a public Ed25519 trust key")
    s.add_argument("--trusted-root", help="Verify release through a trusted-root policy JSON")

    s = sub.add_parser("release-check", help="Run release hygiene and cross-platform checks")
    s.add_argument("repo")
    s.add_argument("--deep", action="store_true", help="Also verify/decompress every chunk")
    s.add_argument("--json-out", help="Optional path to write the same report JSON")

    s = sub.add_parser("extract", help="Extract one path from a local or HTTP .cldrepo")
    s.add_argument("repo")
    s.add_argument("--path", required=True)
    s.add_argument("--out", required=True)
    s.add_argument("--no-verify", action="store_true")
    s.add_argument("--mirror", action="append", default=[], help="Additional HTTP mirror/base URL for pack range reads; repeatable")
    s.add_argument("--mirror-policy", choices=["ordered", "hedged"], default="ordered")
    s.add_argument("--hedge-delay-ms", type=int, default=0, help="Delay before launching a hedged mirror request")
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--mirror-blacklist-threshold", type=int, default=0, help="Temporarily deprioritize a mirror after N chunk failures; 0 disables")
    s.add_argument("--mirror-blacklist-seconds", type=float, default=1.0, help="Temporary in-memory mirror blacklist duration")
    s.add_argument("--bandwidth-limit", default="0", help="Optional cooperative bandwidth cap, e.g. 2MiB; 0 disables")
    s.add_argument("--mirror-state", help="Persist/load mirror scores in this JSON file")

    s = sub.add_parser("diff", help="Compare two repos and estimate delta download")
    s.add_argument("old_repo")
    s.add_argument("new_repo")
    s.add_argument("--out")
    s.add_argument("--patch-plan-out", help="Write an enforceable patch plan JSON")

    s = sub.add_parser("fetch", help="Install/fetch all files from a local or HTTP repo")
    s.add_argument("repo")
    s.add_argument("--install", required=True)
    s.add_argument("--cache")
    s.add_argument("--from-installed", help="Seed reusable chunks from an existing installation directory")
    s.add_argument("--no-verify", action="store_true")
    s.add_argument("--allow-downgrade", action="store_true", help="Allow installing a lower release sequence")
    s.add_argument("--patch-plan", help="Constrain downloads to chunks authorized by a patch plan")
    s.add_argument("--trust-key", help="Require and verify signatures.json before install using a public key")
    s.add_argument("--trusted-root", help="Require and verify release through a trusted-root policy JSON")
    s.add_argument("--mirror", action="append", default=[], help="Additional HTTP mirror/base URL for pack range reads; repeatable")
    s.add_argument("--mirror-policy", choices=["ordered", "hedged"], default="ordered", help="ordered tries mirrors in order; hedged races primary against first mirror")
    s.add_argument("--hedge-delay-ms", type=int, default=0, help="Delay before launching hedged mirror request")
    s.add_argument("--fail-after-chunks", type=int, help=argparse.SUPPRESS)
    s.add_argument("--http-retries", type=int, default=3, help="HTTP retry attempts for metadata/range reads")
    s.add_argument("--http-backoff", type=float, default=0.05, help="Initial HTTP retry backoff in seconds")
    s.add_argument("--parallel", type=int, default=1, help="Parallel chunk prefetch workers; 1 keeps serial behavior")
    s.add_argument("--mirror-blacklist-threshold", type=int, default=0, help="Temporarily deprioritize a mirror after N chunk failures; 0 disables")
    s.add_argument("--mirror-blacklist-seconds", type=float, default=1.0, help="Temporary in-memory mirror blacklist duration")
    s.add_argument("--bandwidth-limit", default="0", help="Optional cooperative bandwidth cap, e.g. 2MiB; 0 disables")
    s.add_argument("--mirror-state", help="Persist/load mirror scores in this JSON file")
    s.add_argument("--stale-lock-seconds", type=float, default=3600.0, help="Treat install locks older than this as stale")

    s = sub.add_parser("keygen", help="Generate an Ed25519 signing key and public trust key")
    s.add_argument("--out", required=True)
    s.add_argument("--pub-out", help="Where to write the public trust key JSON; default: <out>.pub.json")

    s = sub.add_parser("sign", help="Sign a local repo with an Ed25519 private key")
    s.add_argument("repo")
    s.add_argument("--key", required=True)

    s = sub.add_parser("root-init", help="Create a trusted-root policy from one or more public keys")
    s.add_argument("--out", required=True)
    s.add_argument("--key", action="append", required=True, help="Public key JSON to trust; repeatable")
    s.add_argument("--root-id", default="default")
    s.add_argument("--expires-at", help="Optional root expiry timestamp, e.g. 2035-01-01T00:00:00Z")
    s.add_argument("--min-release-seq", type=int, default=0)
    s.add_argument("--allow-unsigned", action="store_true", help="Set require_signature=false in the trusted root")
    s.add_argument("--mirror-url", action="append", default=[], help="Allowed repo/mirror base URL in trusted-root policy; repeatable")


    s = sub.add_parser("audit-install", help="Audit an installed directory against a repo manifest")
    s.add_argument("repo")
    s.add_argument("--install", required=True)

    s = sub.add_parser("repair-install", help="Repair/rebuild an installed directory atomically using repo chunks and cache")
    s.add_argument("repo")
    s.add_argument("--install", required=True)
    s.add_argument("--cache")
    s.add_argument("--trust-key")
    s.add_argument("--trusted-root")
    s.add_argument("--mirror", action="append", default=[])
    s.add_argument("--mirror-policy", choices=["ordered", "hedged"], default="ordered")
    s.add_argument("--hedge-delay-ms", type=int, default=0)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--mirror-state")


    s = sub.add_parser("doctor", help="Inspect/clean CLD2 install crash leftovers: stale lock, staging, backup and optional audit/cache")
    s.add_argument("--install", required=True)
    s.add_argument("--repo", help="Optional repo to audit installed files against")
    s.add_argument("--cache", help="Optional cache directory to index/audit")
    s.add_argument("--fix", action="store_true", help="Remove stale staging dirs/backups/locks when safe")
    s.add_argument("--stale-seconds", type=float, default=0.0, help="Minimum age before fixing leftovers; 0 means fix immediately")

    s = sub.add_parser("cache-index", help="Rebuild and audit a CLD2 raw chunk cache index")
    s.add_argument("cache")
    s.add_argument("--prune-bad", action="store_true")

    s = sub.add_parser("cache-gc", help="Prune a CLD2 raw chunk cache to a max byte budget")
    s.add_argument("cache")
    s.add_argument("--max-bytes", default="0", help="Maximum cache size, e.g. 10GiB; 0 only rebuilds the index")
    s.add_argument("--min-age-seconds", type=float, default=0.0)

    s = sub.add_parser("serve", help="Serve a repo/directory over HTTP with Range support")
    s.add_argument("directory")
    s.add_argument("--port", type=int, default=9387)
    s.add_argument("--bind", default="127.0.0.1")
    s.add_argument("--fail-every", type=int, default=0, help="Test server: return an injected failure every N requests")
    s.add_argument("--fail-status", type=int, default=503, help="Test server: HTTP status used by --fail-every")
    s.add_argument("--truncate-every", type=int, default=0, help="Test server: truncate every Nth range response")
    s.add_argument("--delay-ms", type=int, default=0, help="Test server: delay each request by N milliseconds")

    s = sub.add_parser("bench", help="Run a reproducible CLD2 benchmark for one scenario/profile")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--scenario", choices=BENCH_SCENARIOS, default="game-patch-insert")
    s.add_argument("--profile", choices=sorted(BENCH_PROFILES), default="quick", help="Corpus/pack profile. Use medium/large for heavier tests.")
    s.add_argument("--files", type=int, help="Override file count")
    s.add_argument("--file-size", help="Override primary asset size, e.g. 2MiB")
    s.add_argument("--change-ratio", type=float, help="Override fraction of files changed")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear", "both"], default="both")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="auto")
    s.add_argument("--report-md")
    s.add_argument("--report-csv")

    s = sub.add_parser("bench-matrix", help="Run a multi-scenario benchmark matrix and aggregate reports")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--profile", choices=sorted(BENCH_PROFILES), default="quick")
    s.add_argument("--scenarios", default="game-patch-insert,dataset-model,media-catalog,random-worstcase", help="Comma-separated benchmark scenarios or 'all'")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear", "both"], default="both")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="auto")

    s = sub.add_parser("selftest", help="Run embedded in-process smoke tests")
    s.add_argument("--full", action="store_true", help="Also run the quick synthetic benchmark")
    s.add_argument("--keep-workdir", action="store_true", help="Keep temporary work directory for debugging")
    s.add_argument("--json-out", help="Write selftest report JSON")

    s = sub.add_parser("dist-check", help="Check release ZIP/tree hygiene before distribution")
    s.add_argument("path", nargs="?", default=".")
    s.add_argument("--run-selftest", action="store_true", help="Also run embedded selftest")
    s.add_argument("--json-out", help="Write dist-check report JSON")


    s = sub.add_parser("beta-report", help="Create a beta-readiness dossier with dist-check, optional selftest and benchmark matrix")
    s.add_argument("--path", default=".", help="Source tree to check; default current directory")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--skip-selftest", action="store_true")
    s.add_argument("--skip-benchmarks", action="store_true")
    s.add_argument("--profile", choices=sorted(BENCH_PROFILES), default="quick")
    s.add_argument("--scenarios", default="game-patch-insert,dataset-model,media-catalog,random-worstcase")
    s.add_argument("--download-count", type=int, default=1000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")

    s = sub.add_parser("bench-real", help="Benchmark a real old/new directory pair and generate technical/business reports")
    s.add_argument("--old-dir", required=True, help="Previous release/content directory")
    s.add_argument("--new-dir", required=True, help="New release/content directory")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--scenario-name", default="real-directory-pair")
    s.add_argument("--profile", choices=sorted(BENCH_PROFILES), default="medium", help="Packing/chunk-size profile used for fixed and CDC repos")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear", "both"], default="both")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="auto")
    s.add_argument("--download-count", type=int, default=1000, help="Projected number of client downloads/users for cost estimate")
    s.add_argument("--cost-per-gb", type=float, default=0.05, help="Egress cost per GiB used for projection")
    s.add_argument("--currency", default="USD")
    s.add_argument("--skip-heavy-baselines", action="store_true", help="Skip tar.gz/tar.zst baselines; useful for huge single-file tests")
    s.add_argument("--scenario-kind", help="Optional scenario label, e.g. large-file-middle-insert or random-worstcase")
    s.add_argument("--scenario-note", help="Optional human-readable note stored in report metadata")

    s = sub.add_parser("bench-fastcdc-tune", help="Run a large-file FastCDC tuning matrix on a real old/new pair")
    s.add_argument("--old-dir", required=True, help="Previous release/content directory")
    s.add_argument("--new-dir", required=True, help="New release/content directory")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--profiles", default="large-file-small,large-file-balanced,large-file-large", help="Comma-separated large-file profiles to test")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="raw")
    s.add_argument("--scenario-name", default="fastcdc-tuning")
    s.add_argument("--scenario-kind", help="Optional scenario label, e.g. large-file-middle-insert")
    s.add_argument("--scenario-note", help="Optional human-readable note stored in report metadata")
    s.add_argument("--download-count", type=int, default=1000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")
    s.add_argument("--file-level-tar-zstd-bytes", type=int, help="Optional external baseline: changed-files tar.zst bytes, reused instead of regenerating heavy tar.zst")
    s.add_argument("--full-tar-zstd-v2-bytes", type=int, help="Optional external baseline: full v2 tar.zst bytes, reused instead of regenerating heavy tar.zst")
    s.add_argument("--external-baseline-note", help="Optional note explaining the source of external tar.zst baseline values")
    s.add_argument("--no-fixed", action="store_true", help="Do not include fixed 1MiB baseline")


    s = sub.add_parser("bench-adaptive-policy", help="Run a tuning matrix and choose fixed/balanced/large by transparent policy rules")
    s.add_argument("--old-dir", required=True, help="Previous release/content directory")
    s.add_argument("--new-dir", required=True, help="New release/content directory")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--profiles", default="large-file-balanced,large-file-large", help="Comma-separated FastCDC profiles to test")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="raw")
    s.add_argument("--scenario-name", default="adaptive-policy")
    s.add_argument("--scenario-kind")
    s.add_argument("--scenario-note")
    s.add_argument("--download-count", type=int, default=1000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")
    s.add_argument("--file-level-tar-zstd-bytes", type=int, help="Optional external baseline: changed-files tar.zst bytes")
    s.add_argument("--full-tar-zstd-v2-bytes", type=int, help="Optional external baseline: full v2 tar.zst bytes")
    s.add_argument("--external-baseline-note")
    s.add_argument("--download-tolerance-ratio", type=float, default=0.10, help="Default policy: fastest candidate within this ratio of best transfer")
    s.add_argument("--download-tolerance-bytes", type=int, default=268435456, help="Default policy: absolute byte tolerance around best transfer")
    s.add_argument("--fixed-close-ratio", type=float, default=0.10, help="Choose fixed if it is within this ratio of best transfer and faster")


    s = sub.add_parser("bench-standalone-baselines", help="Run standalone comparative benchmark with tar.zst and optional rsync/zsync/casync external baselines")
    s.add_argument("--old-dir", required=True, help="Previous release/content directory")
    s.add_argument("--new-dir", required=True, help="New release/content directory")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--profiles", default="large-file-balanced,large-file-large", help="Comma-separated FastCDC profiles to test")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="raw")
    s.add_argument("--scenario-name", default="standalone-baselines")
    s.add_argument("--scenario-kind")
    s.add_argument("--scenario-note")
    s.add_argument("--download-count", type=int, default=1000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")
    s.add_argument("--file-level-tar-zstd-bytes", type=int, help="External baseline: changed-files tar.zst update bytes")
    s.add_argument("--full-tar-zstd-v2-bytes", type=int, help="External baseline: full v2 tar.zst bytes")
    s.add_argument("--rsync-bytes", type=int, help="Optional externally measured rsync transfer bytes")
    s.add_argument("--zsync-bytes", type=int, help="Optional externally measured zsync transfer bytes")
    s.add_argument("--casync-bytes", type=int, help="Optional externally measured casync transfer bytes")
    s.add_argument("--external-baseline-note")
    s.add_argument("--download-tolerance-ratio", type=float, default=0.10)
    s.add_argument("--download-tolerance-bytes", type=int, default=268435456)
    s.add_argument("--fixed-close-ratio", type=float, default=0.10)




    s = sub.add_parser("bench-cost-aware-planner", help="Run cost-aware planner: transfer cost + one-time pack cost")
    s.add_argument("--old-dir", required=True)
    s.add_argument("--new-dir", required=True)
    s.add_argument("--out-dir", required=True)
    s.add_argument("--profiles", default="large-file-small,large-file-balanced,large-file-large")
    s.add_argument("--codecs", default="raw,zstd")
    s.add_argument("--scenario-name", default="cost-aware-planner")
    s.add_argument("--scenario-kind")
    s.add_argument("--scenario-note")
    s.add_argument("--download-count", type=int, default=1000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")
    s.add_argument("--pack-cost-per-hour", type=float, default=25.0)
    s.add_argument("--file-level-tar-zstd-bytes", type=int)
    s.add_argument("--full-tar-zstd-v2-bytes", type=int)
    s.add_argument("--rsync-bytes", type=int)
    s.add_argument("--zsync-bytes", type=int)
    s.add_argument("--casync-bytes", type=int)
    s.add_argument("--external-baseline-note")
    s.add_argument("--byte-tolerance-ratio", type=float, default=0.05)
    s.add_argument("--download-tolerance-ratio", type=float, default=0.10)
    s.add_argument("--download-tolerance-bytes", type=int, default=268435456)

    s = sub.add_parser("bench-cost-aware-scenarios", help="Run cost-aware planner once, then rescore internal/public/massive scenarios and compute break-even downloads")
    s.add_argument("--old-dir", required=True)
    s.add_argument("--new-dir", required=True)
    s.add_argument("--out-dir", required=True)
    s.add_argument("--profiles", default="large-file-small,large-file-balanced,large-file-large")
    s.add_argument("--codecs", default="raw,zstd")
    s.add_argument("--scenario-name", default="cost-aware-scenarios")
    s.add_argument("--scenario-kind")
    s.add_argument("--scenario-note")
    s.add_argument("--internal-download-count", type=int, default=10)
    s.add_argument("--public-download-count", type=int, default=10000)
    s.add_argument("--massive-download-count", type=int, default=100000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")
    s.add_argument("--pack-cost-per-hour", type=float, default=25.0)
    s.add_argument("--file-level-tar-zstd-bytes", type=int)
    s.add_argument("--full-tar-zstd-v2-bytes", type=int)
    s.add_argument("--rsync-bytes", type=int)
    s.add_argument("--zsync-bytes", type=int)
    s.add_argument("--casync-bytes", type=int)
    s.add_argument("--external-baseline-note")
    s.add_argument("--byte-tolerance-ratio", type=float, default=0.05)
    s.add_argument("--download-tolerance-ratio", type=float, default=0.10)
    s.add_argument("--download-tolerance-bytes", type=int, default=268435456)
    s.add_argument("--make-light-zip", action="store_true", help="Also write a broad report-only ZIP containing JSON/CSV/MD/TXT/LOG/SHA256 reports, preserving relative paths")
    s.add_argument("--make-review-zip", action="store_true", help="Also write a compact AI/human review ZIP with only high-value result/report files and no generated repo metadata")
    s.add_argument("--light-zip-max-mb", type=float, default=50.0)

    s = sub.add_parser("bench-corpus", help="Run corpus benchmark/falsification matrix across favorable and adversarial scenarios")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--corpus", default="localized-large,distributed-large,append-only-log,many-small-files,high-entropy-rewrite,rename-move")
    s.add_argument("--file-size", default="4MiB")
    s.add_argument("--small-file-count", type=int, default=64)
    s.add_argument("--profiles", default="large-file-small,large-file-balanced,large-file-large")
    s.add_argument("--codecs", default="raw,zstd")
    s.add_argument("--internal-download-count", type=int, default=10)
    s.add_argument("--public-download-count", type=int, default=10000)
    s.add_argument("--massive-download-count", type=int, default=100000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")
    s.add_argument("--pack-cost-per-hour", type=float, default=25.0)
    s.add_argument("--generate-tar-zst", action="store_true", default=True, help="Generate tar.zst baselines for each corpus scenario")
    s.add_argument("--no-generate-tar-zst", action="store_false", dest="generate_tar_zst", help="Skip tar.zst baselines for faster smoke tests")
    s.add_argument("--keep-heavy", action="store_true", help="Keep generated repos/packs inside scenario outputs; default prunes heavy internals after collecting reports")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--review-zip-max-mb", type=float, default=25.0)

    s = sub.add_parser("make-light-zip", help="Create a broad report-only ZIP from an existing benchmark directory, preserving relative paths and avoiding duplicate root names")
    s.add_argument("--src-dir", required=True)
    s.add_argument("--zip-out", required=True)
    s.add_argument("--max-mb", type=float, default=50.0)

    s = sub.add_parser("make-review-zip", help="Create a compact review ZIP from an existing benchmark directory, excluding generated repo metadata/packs")
    s.add_argument("--src-dir", required=True)
    s.add_argument("--zip-out", required=True)
    s.add_argument("--max-mb", type=float, default=10.0)

    s = sub.add_parser("render-report", help="Render a static HTML/Markdown report from corpus or scenario benchmark results")
    s.add_argument("--src-dir", required=True)
    s.add_argument("--out-dir", required=True)
    s.add_argument("--title", default="CLD2 benchmark report")
    s.add_argument("--make-review-zip", action="store_true", help="Also create a compact review ZIP of the rendered report directory")
    s.add_argument("--max-mb", type=float, default=10.0)

    s = sub.add_parser("bench-network-pilot", help="Run local HTTP Range/ETag pilot with pack, fetch, cache reuse and static report")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="8MiB")
    s.add_argument("--bind", default="127.0.0.1")
    s.add_argument("--port", type=int, default=0, help="0 chooses an ephemeral local port")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true", help="Keep repos/install/cache in the output; default keeps them for reproducibility")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-mirror-pilot", help="Run local HTTP mirror/fallback robustness pilot")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="8MiB")
    s.add_argument("--bind", default="127.0.0.1")
    s.add_argument("--primary-port", type=int, default=0, help="0 chooses an ephemeral local port")
    s.add_argument("--mirror-port", type=int, default=0, help="0 chooses an ephemeral local port")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=1)
    s.add_argument("--http-backoff", type=float, default=0.02)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--primary-truncate-every", type=int, default=1, help="Inject partial Range reads on primary every N requests; 0 disables")
    s.add_argument("--primary-delay-ms", type=int, default=0)
    s.add_argument("--mirror-delay-ms", type=int, default=0)
    s.add_argument("--mirror-policy", default="ordered", choices=["ordered", "hedged"])
    s.add_argument("--hedge-delay-ms", type=float, default=25.0)
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-object-store-pilot", help="Run local object-store/S3-style bucket layout pilot")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="8MiB")
    s.add_argument("--bind", default="127.0.0.1")
    s.add_argument("--port", type=int, default=0, help="0 chooses an ephemeral local port")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-signed-url-pilot", help="Run local signed-prefix URL policy pilot")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="8MiB")
    s.add_argument("--bind", default="127.0.0.1")
    s.add_argument("--port", type=int, default=0, help="0 chooses an ephemeral local port")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--ttl-seconds", type=int, default=3600)
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-minio-pilot", help="Run MinIO/S3-compatible pilot through the MinIO mc CLI")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="8MiB")
    s.add_argument("--endpoint", default="", help="MinIO/S3 endpoint, e.g. http://127.0.0.1:9000")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="", help="Base public URL for anonymous GET, default endpoint/bucket")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true", help="Assume objects are already uploaded and only fetch/install")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-minio-robustness", help="Run MinIO cold/warm robustness report")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="8MiB")
    s.add_argument("--endpoint", default="", help="MinIO/S3 endpoint, e.g. http://127.0.0.1:9000")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-minio-full-baseline", help="Run MinIO full-object baseline + cost model")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="8MiB")
    s.add_argument("--endpoint", default="", help="MinIO/S3 endpoint, e.g. http://127.0.0.1:9000")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--cost-per-gb", type=float, default=0.04)
    s.add_argument("--download-counts", default="1,10,1000,10000", help="Comma-separated download counts for cost model")
    s.add_argument("--currency", default="EUR")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-minio-cost-matrix", help="Run MinIO cost matrix across corpus scenarios")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="64MiB")
    s.add_argument("--scenarios", default="normal,high-entropy,small-files", help="Comma-separated: normal,high-entropy,small-files,heavy-change")
    s.add_argument("--small-file-count", type=int, default=256)
    s.add_argument("--endpoint", default="", help="MinIO/S3 endpoint, e.g. http://127.0.0.1:9000")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--cost-per-gb", type=float, default=0.04)
    s.add_argument("--download-counts", default="1,10,1000,10000,100000", help="Comma-separated download counts for cost model")
    s.add_argument("--currency", default="EUR")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-anti-cherrypick-report", help="Run MinIO matrix + anti-cherry-picking claims report")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="64MiB")
    s.add_argument("--scenarios", default="normal,high-entropy,small-files,heavy-change")
    s.add_argument("--small-file-count", type=int, default=256)
    s.add_argument("--endpoint", default="", help="MinIO/S3 endpoint, e.g. http://127.0.0.1:9000")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--cost-per-gb", type=float, default=0.04)
    s.add_argument("--download-counts", default="1,10,1000,10000,100000")
    s.add_argument("--currency", default="EUR")
    s.add_argument("--strong-threshold", type=float, default=0.50, help="Savings ratio >= threshold is a strong-win scenario")
    s.add_argument("--weak-threshold", type=float, default=0.10, help="Savings ratio >= threshold is a weak/moderate win")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-github-report", help="Run GitHub/vetrina technical report generator")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="64MiB")
    s.add_argument("--scenarios", default="normal,high-entropy,small-files,heavy-change")
    s.add_argument("--small-file-count", type=int, default=256)
    s.add_argument("--endpoint", default="", help="MinIO/S3 endpoint, e.g. http://127.0.0.1:9000")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--cost-per-gb", type=float, default=0.04)
    s.add_argument("--download-counts", default="1,10,1000,10000,100000")
    s.add_argument("--currency", default="EUR")
    s.add_argument("--project-name", default="CoreLangDistribution 2.0")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-comparison-harness", help="Run baseline tools preflight + comparison research pack")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="64MiB")
    s.add_argument("--scenarios", default="normal,high-entropy,small-files,heavy-change")
    s.add_argument("--small-file-count", type=int, default=256)
    s.add_argument("--endpoint", default="", help="MinIO/S3 endpoint, e.g. http://127.0.0.1:9000")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--cost-per-gb", type=float, default=0.04)
    s.add_argument("--download-counts", default="1,10,1000,10000,100000")
    s.add_argument("--currency", default="EUR")
    s.add_argument("--project-name", default="CoreLangDistribution 2.0")
    s.add_argument("--probe-only", action="store_true", help="Only probe baseline tools, do not run CLD2 MinIO matrix")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-rsync-baseline", help="Run rsync direct baseline against CLD2 MinIO matrix")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="64MiB")
    s.add_argument("--scenarios", default="normal,high-entropy,small-files,heavy-change")
    s.add_argument("--small-file-count", type=int, default=256)
    s.add_argument("--rsync-path", default="rsync")
    s.add_argument("--probe-only", action="store_true", help="Only check rsync availability and write report")
    s.add_argument("--endpoint", default="", help="MinIO/S3 endpoint, e.g. http://127.0.0.1:9000")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--cost-per-gb", type=float, default=0.04)
    s.add_argument("--download-counts", default="1,10,1000,10000,100000")
    s.add_argument("--currency", default="EUR")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)


    s = sub.add_parser("bench-zsync-baseline", help="Run zsync HTTP delta baseline")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="64MiB")
    s.add_argument("--scenarios", default="normal,high-entropy,small-files,heavy-change")
    s.add_argument("--small-file-count", type=int, default=256)
    s.add_argument("--zsync-path", default="zsync")
    s.add_argument("--zsyncmake-path", default="zsyncmake")
    s.add_argument("--zsync-bind-host", default="0.0.0.0", help="HTTP bind host for zsync local server")
    s.add_argument("--zsync-url-host", default="auto", help="HTTP URL host seen by zsync. Use auto for WSL nameserver detection.")
    s.add_argument("--zsync-server-mode", choices=["auto", "windows", "wsl-native"], default="auto", help="HTTP server placement for zsync baseline")
    s.add_argument("--probe-only", action="store_true", help="Only check zsync/zsyncmake availability and write report")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="zstd")
    s.add_argument("--chunker", choices=["fixed", "cdc", "fastcdc", "gear"], default="fastcdc")
    s.add_argument("--fixed-size", default="1MiB")
    s.add_argument("--chunk-min", default="64KiB")
    s.add_argument("--chunk-avg", default="256KiB")
    s.add_argument("--chunk-max", default="1MiB")
    s.add_argument("--fastcdc-stride", type=int, default=4)
    s.add_argument("--cost-per-gb", type=float, default=0.04)
    s.add_argument("--download-counts", default="1,10,1000,10000,100000")
    s.add_argument("--currency", default="EUR")
    s.add_argument("--endpoint", default="", help="Optional MinIO/S3 endpoint for attached CLD2 matrix")
    s.add_argument("--access-key", default="")
    s.add_argument("--secret-key", default="")
    s.add_argument("--bucket", default="cld2-demo-bucket")
    s.add_argument("--prefix", default="releases")
    s.add_argument("--alias", default="cld2demo")
    s.add_argument("--mc-path", default="mc")
    s.add_argument("--public-base-url", default="")
    s.add_argument("--preflight-only", action="store_true")
    s.add_argument("--skip-upload", action="store_true")
    s.add_argument("--http-retries", type=int, default=3)
    s.add_argument("--http-backoff", type=float, default=0.05)
    s.add_argument("--parallel", type=int, default=1)
    s.add_argument("--cld2-attach-retries", type=int, default=4, help="Retry CLD2 MinIO attach matrix when object store is temporarily unwritable")
    s.add_argument("--cld2-attach-backoff", type=float, default=2.0, help="Base seconds for CLD2 MinIO attach retry backoff")
    s.add_argument("--make-review-zip", action="store_true")
    s.add_argument("--keep-heavy", action="store_true")
    s.add_argument("--max-mb", type=float, default=10.0)

    s = sub.add_parser("cleanup-heavy-artifacts", help="List or remove heavy generated benchmark artifacts while keeping report files")
    s.add_argument("--path", required=True)
    s.add_argument("--min-mb", type=float, default=100.0)
    s.add_argument("--apply", action="store_true", help="Actually delete matching files. Without this flag the command is a dry-run.")

    s = sub.add_parser("bench-hybrid-planner", help="Run codec-aware hybrid planner: fixed/FastCDC across codecs plus tar.zst/external fallbacks")
    s.add_argument("--old-dir", required=True)
    s.add_argument("--new-dir", required=True)
    s.add_argument("--out-dir", required=True)
    s.add_argument("--profiles", default="large-file-small,large-file-balanced,large-file-large")
    s.add_argument("--codecs", default="raw,zstd")
    s.add_argument("--scenario-name", default="hybrid-planner")
    s.add_argument("--scenario-kind")
    s.add_argument("--scenario-note")
    s.add_argument("--download-count", type=int, default=1000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")
    s.add_argument("--file-level-tar-zstd-bytes", type=int)
    s.add_argument("--full-tar-zstd-v2-bytes", type=int)
    s.add_argument("--rsync-bytes", type=int)
    s.add_argument("--zsync-bytes", type=int)
    s.add_argument("--casync-bytes", type=int)
    s.add_argument("--external-baseline-note")
    s.add_argument("--download-tolerance-ratio", type=float, default=0.10)
    s.add_argument("--download-tolerance-bytes", type=int, default=268435456)

    s = sub.add_parser("bench-heavy-change", help="Run heavy-change guardrail matrix with optional tar.zst baselines")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--file-size", default="128MiB")
    s.add_argument("--change-ratios", default="1%,5%,10%,25%")
    s.add_argument("--modes", default="localized,distributed")
    s.add_argument("--profiles", default="large-file-balanced,large-file-large")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="raw")
    s.add_argument("--generate-tar-zst", action="store_true", help="Generate tar.zst baselines when python-zstandard is installed")
    s.add_argument("--download-count", type=int, default=1000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")

    s = sub.add_parser("bench-largefile-variants", help="Run synthetic guardrail variants: middle insert, localized overwrite, random rewrite")
    s.add_argument("--out-dir", required=True)
    s.add_argument("--variants", default="middle-insert,localized-overwrite,random-rewrite-1pct")
    s.add_argument("--profiles", default="large-file-balanced")
    s.add_argument("--file-size", default="32MiB")
    s.add_argument("--codec", choices=["auto", "zstd", "zlib", "raw", "none"], default="raw")
    s.add_argument("--download-count", type=int, default=1000)
    s.add_argument("--cost-per-gb", type=float, default=0.05)
    s.add_argument("--currency", default="USD")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.cmd == "pack":
            emit(make_repo(args.input_dir, args.out, release_id=args.release_id, release_seq=args.release_seq, chunker=args.chunker,
                           fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg,
                           chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, codec=args.codec, force=args.force, expires_at=args.expires_at, not_before=args.not_before))
        elif args.cmd == "inspect":
            emit(inspect_repo(args.repo))
        elif args.cmd == "verify":
            r = verify_repo(args.repo, deep=args.deep, trust_key=args.trust_key, trusted_root=args.trusted_root)
            emit(r)
            return 0 if r["ok"] else 2
        elif args.cmd == "release-check":
            r = release_check(args.repo, deep=args.deep)
            if args.json_out:
                Path(args.json_out).write_text(json.dumps(r, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
            emit(r)
            return 0 if r.get("ok") else 2
        elif args.cmd == "extract":
            emit(extract_file(args.repo, args.path, args.out, verify=not args.no_verify, mirrors=args.mirror, mirror_policy=args.mirror_policy, hedge_delay=args.hedge_delay_ms / 1000.0, http_retries=args.http_retries, http_backoff=args.http_backoff, mirror_blacklist_threshold=args.mirror_blacklist_threshold, mirror_blacklist_seconds=args.mirror_blacklist_seconds, bandwidth_limit_bps=args.bandwidth_limit, mirror_state_file=args.mirror_state))
        elif args.cmd == "diff":
            r = diff_repos(args.old_repo, args.new_repo)
            if args.out:
                Path(args.out).write_text(json.dumps(r, indent=2, sort_keys=True), encoding="utf-8")
            if args.patch_plan_out:
                create_patch_plan(args.old_repo, args.new_repo, args.patch_plan_out)
                r["patch_plan_out"] = args.patch_plan_out
            emit(r)
        elif args.cmd == "fetch":
            emit(fetch_install(args.repo, args.install, cache_dir=args.cache, from_installed=args.from_installed, verify=not args.no_verify, allow_downgrade=args.allow_downgrade, fail_after_chunks=args.fail_after_chunks, patch_plan=args.patch_plan, trust_key=args.trust_key, trusted_root=args.trusted_root, mirrors=args.mirror, mirror_policy=args.mirror_policy, hedge_delay=args.hedge_delay_ms / 1000.0, http_retries=args.http_retries, http_backoff=args.http_backoff, mirror_blacklist_threshold=args.mirror_blacklist_threshold, mirror_blacklist_seconds=args.mirror_blacklist_seconds, bandwidth_limit_bps=args.bandwidth_limit, parallel=args.parallel, mirror_state_file=args.mirror_state, stale_lock_seconds=args.stale_lock_seconds))
        elif args.cmd == "keygen":
            emit(keygen(args.out, pub_out=args.pub_out))
        elif args.cmd == "sign":
            emit(sign_repo(args.repo, args.key))
        elif args.cmd == "root-init":
            emit(root_init(args.out, args.key, root_id=args.root_id, expires_at=args.expires_at, min_release_seq=args.min_release_seq, require_signature=not args.allow_unsigned, mirror_urls=args.mirror_url))
        elif args.cmd == "audit-install":
            r = audit_install(args.repo, args.install)
            emit(r)
            return 0 if r["ok"] else 2
        elif args.cmd == "repair-install":
            emit(repair_install(args.repo, args.install, cache_dir=args.cache, trust_key=args.trust_key, trusted_root=args.trusted_root, mirrors=args.mirror, mirror_policy=args.mirror_policy, hedge_delay=args.hedge_delay_ms / 1000.0, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, mirror_state_file=args.mirror_state, stale_lock_seconds=args.stale_lock_seconds))
        elif args.cmd == "doctor":
            r = doctor_install(args.install, repo_source=args.repo, cache_dir=args.cache, fix=args.fix, stale_seconds=args.stale_seconds)
            emit(r)
            return 0 if r.get("ok") else 2
        elif args.cmd == "cache-index":
            emit(rebuild_cache_index(args.cache, prune_bad=args.prune_bad))
        elif args.cmd == "cache-gc":
            emit(cache_gc(args.cache, max_bytes=args.max_bytes, min_age_seconds=args.min_age_seconds))
        elif args.cmd == "serve":
            serve(args.directory, port=args.port, bind=args.bind, fail_every=args.fail_every, fail_status=args.fail_status, truncate_every=args.truncate_every, delay_ms=args.delay_ms)
        elif args.cmd == "bench":
            emit(run_bench(args.out_dir, chunker=args.chunker, scenario=args.scenario, profile=args.profile, files=args.files, file_size=args.file_size, change_ratio=args.change_ratio, codec=args.codec, report_md=args.report_md, report_csv=args.report_csv))
        elif args.cmd == "bench-matrix":
            scenarios = BENCH_SCENARIOS if args.scenarios.strip().lower() == "all" else [x.strip() for x in args.scenarios.split(",") if x.strip()]
            emit(run_bench_matrix(args.out_dir, scenarios=scenarios, profile=args.profile, chunker=args.chunker, codec=args.codec))
        elif args.cmd == "selftest":
            r = run_selftest(quick=not args.full, keep_workdir=args.keep_workdir)
            if args.json_out:
                Path(args.json_out).write_text(json.dumps(r, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
            emit(r)
            return 0 if r.get("ok") else 2
        elif args.cmd == "dist-check":
            r = dist_check(args.path, run_tests=args.run_selftest)
            if args.json_out:
                write_json_report(args.json_out, r)
            emit(r)
            return 0 if r.get("ok") else 2

        elif args.cmd == "beta-report":
            scenarios = [x.strip() for x in args.scenarios.split(",") if x.strip()]
            r = beta_report(args.path, args.out_dir, run_tests=not args.skip_selftest, run_benchmarks=not args.skip_benchmarks, benchmark_profile=args.profile, scenarios=scenarios, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency)
            emit(r)
            return 0 if r.get("ok") else 2
        elif args.cmd == "bench-real":
            emit(run_real_bench(args.old_dir, args.new_dir, args.out_dir, scenario_name=args.scenario_name, profile=args.profile, chunker=args.chunker, codec=args.codec, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency, skip_heavy_baselines=args.skip_heavy_baselines, scenario_kind=args.scenario_kind, scenario_note=args.scenario_note))
        elif args.cmd == "bench-fastcdc-tune":
            emit(run_fastcdc_tuning_matrix(args.old_dir, args.new_dir, args.out_dir, profiles=args.profiles, codec=args.codec, scenario_name=args.scenario_name, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency, include_fixed=not args.no_fixed, scenario_kind=args.scenario_kind, scenario_note=args.scenario_note, file_level_tar_zstd_bytes=args.file_level_tar_zstd_bytes, full_tar_zstd_v2_bytes=args.full_tar_zstd_v2_bytes, external_baseline_note=args.external_baseline_note))
        elif args.cmd == "bench-adaptive-policy":
            emit(run_adaptive_policy_bench(args.old_dir, args.new_dir, args.out_dir, profiles=args.profiles, codec=args.codec, scenario_name=args.scenario_name, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency, scenario_kind=args.scenario_kind, scenario_note=args.scenario_note, file_level_tar_zstd_bytes=args.file_level_tar_zstd_bytes, full_tar_zstd_v2_bytes=args.full_tar_zstd_v2_bytes, external_baseline_note=args.external_baseline_note, download_tolerance_ratio=args.download_tolerance_ratio, download_tolerance_bytes=args.download_tolerance_bytes, fixed_close_ratio=args.fixed_close_ratio))
        elif args.cmd == "bench-standalone-baselines":
            emit(run_standalone_baselines_bench(args.old_dir, args.new_dir, args.out_dir, profiles=args.profiles, codec=args.codec, scenario_name=args.scenario_name, scenario_kind=args.scenario_kind, scenario_note=args.scenario_note, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency, file_level_tar_zstd_bytes=args.file_level_tar_zstd_bytes, full_tar_zstd_v2_bytes=args.full_tar_zstd_v2_bytes, rsync_bytes=args.rsync_bytes, zsync_bytes=args.zsync_bytes, casync_bytes=args.casync_bytes, external_baseline_note=args.external_baseline_note, download_tolerance_ratio=args.download_tolerance_ratio, download_tolerance_bytes=args.download_tolerance_bytes, fixed_close_ratio=args.fixed_close_ratio))
        elif args.cmd == "bench-cost-aware-planner":
            emit(run_cost_aware_planner_bench(args.old_dir, args.new_dir, args.out_dir, profiles=args.profiles, codecs=args.codecs, scenario_name=args.scenario_name, scenario_kind=args.scenario_kind, scenario_note=args.scenario_note, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency, pack_cost_per_hour=args.pack_cost_per_hour, file_level_tar_zstd_bytes=args.file_level_tar_zstd_bytes, full_tar_zstd_v2_bytes=args.full_tar_zstd_v2_bytes, rsync_bytes=args.rsync_bytes, zsync_bytes=args.zsync_bytes, casync_bytes=args.casync_bytes, external_baseline_note=args.external_baseline_note, byte_tolerance_ratio=args.byte_tolerance_ratio, download_tolerance_ratio=args.download_tolerance_ratio, download_tolerance_bytes=args.download_tolerance_bytes))
        elif args.cmd == "bench-corpus":
            emit(run_corpus_bench(args.out_dir, corpus=args.corpus, file_size=args.file_size, small_file_count=args.small_file_count, profiles=args.profiles, codecs=args.codecs, internal_download_count=args.internal_download_count, public_download_count=args.public_download_count, massive_download_count=args.massive_download_count, cost_per_gb=args.cost_per_gb, currency=args.currency, pack_cost_per_hour=args.pack_cost_per_hour, generate_tar_zst=args.generate_tar_zst, keep_heavy=args.keep_heavy, make_review=args.make_review_zip, review_zip_max_mb=args.review_zip_max_mb))
        elif args.cmd == "bench-cost-aware-scenarios":
            emit(run_cost_aware_scenarios_bench(args.old_dir, args.new_dir, args.out_dir, profiles=args.profiles, codecs=args.codecs, scenario_name=args.scenario_name, scenario_kind=args.scenario_kind, scenario_note=args.scenario_note, internal_download_count=args.internal_download_count, public_download_count=args.public_download_count, massive_download_count=args.massive_download_count, cost_per_gb=args.cost_per_gb, currency=args.currency, pack_cost_per_hour=args.pack_cost_per_hour, file_level_tar_zstd_bytes=args.file_level_tar_zstd_bytes, full_tar_zstd_v2_bytes=args.full_tar_zstd_v2_bytes, rsync_bytes=args.rsync_bytes, zsync_bytes=args.zsync_bytes, casync_bytes=args.casync_bytes, external_baseline_note=args.external_baseline_note, byte_tolerance_ratio=args.byte_tolerance_ratio, download_tolerance_ratio=args.download_tolerance_ratio, download_tolerance_bytes=args.download_tolerance_bytes, make_zip=args.make_light_zip, make_review=args.make_review_zip, light_zip_max_mb=args.light_zip_max_mb))
        elif args.cmd == "make-light-zip":
            emit(make_light_zip(args.src_dir, args.zip_out, max_mb=args.max_mb))
        elif args.cmd == "make-review-zip":
            emit(make_review_zip(args.src_dir, args.zip_out, max_mb=args.max_mb))
        elif args.cmd == "render-report":
            emit(render_static_report(args.src_dir, args.out_dir, title=args.title, make_review=args.make_review_zip, max_mb=args.max_mb))
        elif args.cmd == "bench-network-pilot":
            emit(run_network_pilot(args.out_dir, file_size=args.file_size, bind=args.bind, port=args.port, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cld2_attach_retries=args.cld2_attach_retries, cld2_attach_backoff=args.cld2_attach_backoff, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-mirror-pilot":
            emit(run_mirror_pilot(args.out_dir, file_size=args.file_size, bind=args.bind, primary_port=args.primary_port, mirror_port=args.mirror_port, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, primary_truncate_every=args.primary_truncate_every, primary_delay_ms=args.primary_delay_ms, mirror_delay_ms=args.mirror_delay_ms, mirror_policy=args.mirror_policy, hedge_delay=args.hedge_delay_ms / 1000.0, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-object-store-pilot":
            emit(run_object_store_pilot(args.out_dir, file_size=args.file_size, bind=args.bind, port=args.port, bucket=args.bucket, prefix=args.prefix, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cld2_attach_retries=args.cld2_attach_retries, cld2_attach_backoff=args.cld2_attach_backoff, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-signed-url-pilot":
            emit(run_signed_url_pilot(args.out_dir, file_size=args.file_size, bind=args.bind, port=args.port, bucket=args.bucket, prefix=args.prefix, ttl_seconds=args.ttl_seconds, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cld2_attach_retries=args.cld2_attach_retries, cld2_attach_backoff=args.cld2_attach_backoff, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-minio-pilot":
            emit(run_minio_pilot(args.out_dir, file_size=args.file_size, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cld2_attach_retries=args.cld2_attach_retries, cld2_attach_backoff=args.cld2_attach_backoff, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-minio-robustness":
            emit(run_minio_robustness_pilot(args.out_dir, file_size=args.file_size, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cld2_attach_retries=args.cld2_attach_retries, cld2_attach_backoff=args.cld2_attach_backoff, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-minio-full-baseline":
            emit(run_minio_full_baseline_pilot(args.out_dir, file_size=args.file_size, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cost_per_gb=args.cost_per_gb, download_counts=args.download_counts, currency=args.currency, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-minio-cost-matrix":
            emit(run_minio_cost_matrix_pilot(args.out_dir, file_size=args.file_size, scenarios=args.scenarios, small_file_count=args.small_file_count, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cost_per_gb=args.cost_per_gb, download_counts=args.download_counts, currency=args.currency, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-anti-cherrypick-report":
            emit(run_anti_cherrypick_report_pilot(args.out_dir, file_size=args.file_size, scenarios=args.scenarios, small_file_count=args.small_file_count, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cost_per_gb=args.cost_per_gb, download_counts=args.download_counts, currency=args.currency, strong_threshold=args.strong_threshold, weak_threshold=args.weak_threshold, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-github-report":
            emit(run_github_report_pilot(args.out_dir, file_size=args.file_size, scenarios=args.scenarios, small_file_count=args.small_file_count, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cost_per_gb=args.cost_per_gb, download_counts=args.download_counts, currency=args.currency, project_name=args.project_name, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-comparison-harness":
            emit(run_comparison_harness_pilot(args.out_dir, file_size=args.file_size, scenarios=args.scenarios, small_file_count=args.small_file_count, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cost_per_gb=args.cost_per_gb, download_counts=args.download_counts, currency=args.currency, project_name=args.project_name, probe_only=args.probe_only, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-rsync-baseline":
            emit(run_rsync_baseline_pilot(args.out_dir, file_size=args.file_size, scenarios=args.scenarios, small_file_count=args.small_file_count, rsync_path=args.rsync_path, probe_only=args.probe_only, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cost_per_gb=args.cost_per_gb, download_counts=args.download_counts, currency=args.currency, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "bench-zsync-baseline":
            emit(run_zsync_baseline_pilot(args.out_dir, file_size=args.file_size, scenarios=args.scenarios, small_file_count=args.small_file_count, zsync_path=args.zsync_path, zsyncmake_path=args.zsyncmake_path, zsync_bind_host=args.zsync_bind_host, zsync_url_host=args.zsync_url_host, zsync_server_mode=args.zsync_server_mode, probe_only=args.probe_only, codec=args.codec, chunker=args.chunker, fixed_size=args.fixed_size, chunk_min=args.chunk_min, chunk_avg=args.chunk_avg, chunk_max=args.chunk_max, fastcdc_stride=args.fastcdc_stride, cost_per_gb=args.cost_per_gb, download_counts=args.download_counts, currency=args.currency, endpoint=args.endpoint, access_key=args.access_key, secret_key=args.secret_key, bucket=args.bucket, prefix=args.prefix, alias=args.alias, mc_path=args.mc_path, public_base_url=args.public_base_url, preflight_only=args.preflight_only, skip_upload=args.skip_upload, http_retries=args.http_retries, http_backoff=args.http_backoff, parallel=args.parallel, cld2_attach_retries=args.cld2_attach_retries, cld2_attach_backoff=args.cld2_attach_backoff, make_review=args.make_review_zip, keep_heavy=args.keep_heavy, max_mb=args.max_mb))
        elif args.cmd == "cleanup-heavy-artifacts":
            emit(cleanup_heavy_artifacts(args.path, min_mb=args.min_mb, apply=args.apply))
        elif args.cmd == "bench-hybrid-planner":
            emit(run_hybrid_planner_bench(args.old_dir, args.new_dir, args.out_dir, profiles=args.profiles, codecs=args.codecs, scenario_name=args.scenario_name, scenario_kind=args.scenario_kind, scenario_note=args.scenario_note, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency, file_level_tar_zstd_bytes=args.file_level_tar_zstd_bytes, full_tar_zstd_v2_bytes=args.full_tar_zstd_v2_bytes, rsync_bytes=args.rsync_bytes, zsync_bytes=args.zsync_bytes, casync_bytes=args.casync_bytes, external_baseline_note=args.external_baseline_note, download_tolerance_ratio=args.download_tolerance_ratio, download_tolerance_bytes=args.download_tolerance_bytes))
        elif args.cmd == "bench-heavy-change":
            emit(run_heavy_change_matrix(args.out_dir, file_size=args.file_size, change_ratios=args.change_ratios, modes=args.modes, profiles=args.profiles, codec=args.codec, generate_tar_zst=args.generate_tar_zst, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency))
        elif args.cmd == "bench-largefile-variants":
            emit(run_largefile_variant_matrix(args.out_dir, variants=args.variants, profiles=args.profiles, file_size=args.file_size, codec=args.codec, cost_per_gb=args.cost_per_gb, download_count=args.download_count, currency=args.currency))
        return 0
    except Exception as e:
        print(f"cld2 error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
