#!/usr/bin/env python3
"""Run CLD2 alpha55 public examples matrix.

This script assumes example v1/v2 directories were generated by
alpha55_make_public_examples.py. It runs pack/fetch/audit and writes JSON/CSV/MD
summary outputs.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

CASES = ["game_asset_patch", "model_profile_pack", "ci_artifact_bundle"]


def run(cmd: list[str], cwd: Path, timeout: int = 1800) -> dict:
    t0 = time.time()
    p = subprocess.run(cmd, cwd=str(cwd), text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
    parsed = None
    # CLD2 often prints JSON. Try to parse the whole output or the last JSON object.
    out = p.stdout.strip()
    if out:
        try:
            parsed = json.loads(out)
        except Exception:
            start = out.rfind("{")
            if start >= 0:
                try:
                    parsed = json.loads(out[start:])
                except Exception:
                    parsed = None
    return {
        "cmd": cmd,
        "returncode": p.returncode,
        "ok": p.returncode == 0,
        "seconds": round(time.time() - t0, 3),
        "stdout_tail": p.stdout[-8000:],
        "stderr_tail": p.stderr[-8000:],
        "parsed_json": parsed,
    }


def tree_digest(root: Path, exclude_dirs: set[str] | None = None) -> dict:
    exclude_dirs = exclude_dirs or set()
    h = hashlib.sha256()
    count = 0
    total = 0
    files = []
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        parts = p.relative_to(root).parts
        if any(part in exclude_dirs for part in parts):
            continue
        data = p.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        rel = p.relative_to(root).as_posix()
        h.update(rel.encode("utf-8"))
        h.update(b"\0")
        h.update(digest.encode("ascii"))
        h.update(b"\n")
        count += 1
        total += len(data)
        files.append({"path": rel, "bytes": len(data), "sha256": digest})
    return {"sha256": h.hexdigest(), "files": count, "bytes": total, "file_list": files[:50]}


def extract_fetch_metrics(parsed: dict | None) -> dict:
    metrics = {
        "downloaded_pack_bytes": None,
        "downloaded_chunks": None,
        "reused_cache_raw_bytes": None,
        "cache_hit_chunks": None,
        "resumed_from_cache": None,
        "seeded_chunks": None,
    }
    if not isinstance(parsed, dict):
        return metrics
    for k in list(metrics):
        if k in parsed:
            metrics[k] = parsed.get(k)
    # Some older outputs nest fetch info.
    for nest in ["fetch", "result", "install", "summary"]:
        obj = parsed.get(nest)
        if isinstance(obj, dict):
            for k in list(metrics):
                if metrics[k] is None and k in obj:
                    metrics[k] = obj.get(k)
    return metrics


def classify(row: dict) -> str:
    ok = row.get("ok")
    if not ok:
        return "failed"
    full = row.get("full_v2_payload_bytes") or 0
    warm = row.get("warm_downloaded_pack_bytes")
    if warm is None:
        return "pass_metrics_unavailable"
    try:
        ratio = float(warm) / float(full) if full else 1.0
    except Exception:
        return "pass_metrics_unavailable"
    if ratio <= 0.05:
        return "high-reuse-win"
    if ratio <= 0.35:
        return "moderate-win"
    if ratio <= 0.85:
        return "partial-win"
    return "near-parity-or-bad-fit"


def run_case(repo_root: Path, examples_root: Path, out_root: Path, case: str) -> dict:
    case_src = examples_root / case
    v1 = case_src / "v1"
    v2 = case_src / "v2"
    case_out = out_root / case
    if case_out.exists():
        shutil.rmtree(case_out)
    case_out.mkdir(parents=True)

    repo_v1 = case_out / "v1.cldrepo"
    repo_v2 = case_out / "v2.cldrepo"
    cache = case_out / "cache"
    install_v1 = case_out / "install_v1"
    install_v2 = case_out / "install_v2"

    expected_v2 = tree_digest(v2)

    pack_v1 = run([sys.executable, str(repo_root / "cld2.py"), "pack", str(v1), "--out", str(repo_v1), "--release-id", f"alpha55-{case}", "--release-seq", "1", "--force"], cwd=repo_root)
    pack_v2 = run([sys.executable, str(repo_root / "cld2.py"), "pack", str(v2), "--out", str(repo_v2), "--release-id", f"alpha55-{case}", "--release-seq", "2", "--force"], cwd=repo_root)

    fetch_v1 = run([sys.executable, str(repo_root / "cld2.py"), "fetch", str(repo_v1), "--install", str(install_v1), "--cache", str(cache)], cwd=repo_root)
    fetch_v2 = run([sys.executable, str(repo_root / "cld2.py"), "fetch", str(repo_v2), "--install", str(install_v2), "--cache", str(cache)], cwd=repo_root)
    audit_v2 = run([sys.executable, str(repo_root / "cld2.py"), "audit-install", str(repo_v2), "--install", str(install_v2)], cwd=repo_root)

    actual_v2 = tree_digest(install_v2, exclude_dirs={".cld2"}) if install_v2.exists() else {"sha256": None, "files": 0, "bytes": 0}
    digest_ok = expected_v2["sha256"] == actual_v2["sha256"]
    metrics_v2 = extract_fetch_metrics(fetch_v2.get("parsed_json"))

    ok = all([pack_v1["ok"], pack_v2["ok"], fetch_v1["ok"], fetch_v2["ok"], audit_v2["ok"], digest_ok])

    row = {
        "scenario": case,
        "ok": ok,
        "pack_v1_ok": pack_v1["ok"],
        "pack_v2_ok": pack_v2["ok"],
        "fetch_v1_ok": fetch_v1["ok"],
        "fetch_v2_ok": fetch_v2["ok"],
        "audit_v2_ok": audit_v2["ok"],
        "digest_ok": digest_ok,
        "full_v2_payload_bytes": expected_v2["bytes"],
        "full_v2_file_count": expected_v2["files"],
        "expected_tree_sha256": expected_v2["sha256"],
        "actual_tree_sha256": actual_v2["sha256"],
        "warm_downloaded_pack_bytes": metrics_v2.get("downloaded_pack_bytes"),
        "warm_downloaded_chunks": metrics_v2.get("downloaded_chunks"),
        "warm_reused_cache_raw_bytes": metrics_v2.get("reused_cache_raw_bytes"),
        "warm_cache_hit_chunks": metrics_v2.get("cache_hit_chunks"),
        "warm_resumed_from_cache": metrics_v2.get("resumed_from_cache"),
        "warm_seeded_chunks": metrics_v2.get("seeded_chunks"),
        "classification": None,
    }
    row["classification"] = classify(row)

    result = {
        "schema": "CLD2/alpha55_public_example_result",
        "code_baseline": "2.0.0-alpha50.2",
        "benchmark_milestone": "alpha55",
        "scenario": case,
        "row": row,
        "expected_v2": expected_v2,
        "actual_v2": actual_v2,
        "commands": {
            "pack_v1": pack_v1,
            "pack_v2": pack_v2,
            "fetch_v1": fetch_v1,
            "fetch_v2": fetch_v2,
            "audit_v2": audit_v2,
        },
        "claim_boundary": [
            "Local generated public example.",
            "Not a cloud/CDN/S3/MinIO benchmark.",
            "Use as showcase and fit-test harness only.",
        ],
    }
    (case_out / "alpha55_public_example_result.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return result


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", required=True)
    ap.add_argument("--examples-root", required=True)
    ap.add_argument("--out-root", required=True)
    args = ap.parse_args()

    repo_root = Path(args.repo_root).resolve()
    examples_root = Path(args.examples_root).resolve()
    out_root = Path(args.out_root).resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    results = []
    rows = []
    for case in CASES:
        print(f"=== alpha55 scenario: {case} ===", flush=True)
        result = run_case(repo_root, examples_root, out_root, case)
        results.append(result)
        rows.append(result["row"])

    summary = {
        "schema": "CLD2/alpha55_public_examples_summary",
        "code_baseline": "2.0.0-alpha50.2",
        "benchmark_milestone": "alpha55",
        "overall_ok": all(r["row"]["ok"] for r in results),
        "scenarios": rows,
        "claim_boundary": [
            "Alpha55 is a public examples/showcase harness.",
            "It is not a production benchmark or external audit.",
            "It helps users see whether their own artifacts resemble good-fit warm updates.",
        ],
    }
    (out_root / "alpha55_public_examples_summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    csv_path = out_root / "alpha55_public_examples_summary.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        fieldnames = list(rows[0].keys()) if rows else []
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)

    table_lines = []
    for r in rows:
        table_lines.append(
            f"| {r['scenario']} | {r['ok']} | {r['classification']} | {r['full_v2_payload_bytes']} | {r['warm_downloaded_pack_bytes']} | {r['audit_v2_ok']} | {r['digest_ok']} |"
        )
    md = """# CLD2 alpha55 — Public examples report

## Verdict

Overall OK: `{overall_ok}`

## Summary

| Scenario | OK | Classification | full v2 payload bytes | warm downloaded pack bytes | audit OK | digest OK |
|---|---:|---|---:|---:|---:|---:|
{rows}

## Claim boundary

These are local generated public examples. They are not a cloud/CDN/S3/MinIO performance benchmark and not an external security audit.
""".format(overall_ok=summary["overall_ok"], rows="\n".join(table_lines))
    (out_root / "ALPHA55_PUBLIC_EXAMPLES_REPORT.md").write_text(md, encoding="utf-8")

    print(json.dumps({"ok": summary["overall_ok"], "out_root": str(out_root), "scenarios": rows}, indent=2, sort_keys=True))
    return 0 if summary["overall_ok"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
